name: Draft release

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-draft
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: |
          exec 19> >( sed -e's/^/::debug::/g' )
          BASH_XTRACEFD=19
          export DEBUG=api
          set -x

          git checkout --branch next-release
          npm run prepare
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/
          git commit -m 'Build for ${{ steps.release-draft.outputs.tag-name }}'
          git push origin HEAD --force

          RELEASE_URL="repos/${{ github.repository }}/releases/${{ steps.release-draft.outputs.release-id }}"
          gh api -X PATCH "$RELEASE_URL" 2>&19 \
            --field tag_name="$( gh api "$RELEASE_URL" --jq .tag_name 2>&19 )" \
            --field target_commitish=next-release
